// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using WebApplication1.Models;

namespace WebApplication1.Data
{
    public partial interface IGestorRRHHContextProcedures
    {
        Task<int> sp_cambio_claveAsync(string i_usuario, string i_clave_a, string i_clave_n, OutputParameter<long?> o_codigo, OutputParameter<string> o_mensaje, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_loginResult>> sp_loginAsync(string i_usuario, string i_clave, OutputParameter<string> o_name, OutputParameter<long?> o_codigo, OutputParameter<string> o_mensaje, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_nueva_claveAsync(string i_usuario, string i_otp, string i_clave_a, string i_clave_n, OutputParameter<long?> o_codigo, OutputParameter<string> o_mensaje, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
