// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication1.Models
{
    public partial class Catalog
    {
        public Catalog()
        {
            CatalogDetail = new HashSet<CatalogDetail>();
        }

        /// <summary>
        /// ID general del servicio
        /// </summary>
        [Key]
        public long ID { get; set; }
        /// <summary>
        /// Catalog code. Is unique
        /// </summary>
        [Required]
        [StringLength(50)]
        public string catalogCode { get; set; }
        /// <summary>
        /// Catalog name for front end
        /// </summary>
        [Required]
        [StringLength(128)]
        public string catalogName { get; set; }

        [InverseProperty("catalog")]
        public virtual ICollection<CatalogDetail> CatalogDetail { get; set; }
    }
}