// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication1.Models
{
    public partial class CatalogDetail
    {
        [Key]
        public long ID { get; set; }
        /// <summary>
        /// The catalog belong to
        /// </summary>
        public long catalogID { get; set; }
        /// <summary>
        /// Value of the item
        /// </summary>
        [Required]
        [StringLength(50)]
        public string valueDetail { get; set; }
        /// <summary>
        /// Description for the front end
        /// </summary>
        [Required]
        [StringLength(128)]
        public string valueDescription { get; set; }
        /// <summary>
        /// Enabled or not
        /// </summary>
        public bool enabled { get; set; }

        [ForeignKey(nameof(catalogID))]
        [InverseProperty(nameof(Catalog.CatalogDetail))]
        public virtual Catalog catalog { get; set; }
    }
}