// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication1.Models
{
    public partial class Company
    {
        public Company()
        {
            Employee = new HashSet<Employee>();
            UserCompany = new HashSet<UserCompany>();
        }

        [Key]
        public long companyID { get; set; }
        [Required]
        [StringLength(50)]
        public string companyCode { get; set; }
        [Required]
        [StringLength(128)]
        public string companyName { get; set; }

        [InverseProperty("company")]
        public virtual ICollection<Employee> Employee { get; set; }
        [InverseProperty("company")]
        public virtual ICollection<UserCompany> UserCompany { get; set; }
    }
}