// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication1.Models
{
    public partial class Role
    {
        public Role()
        {
            RoleOption = new HashSet<RoleOption>();
            User = new HashSet<User>();
        }

        [Key]
        public long RoleID { get; set; }
        [Required]
        [StringLength(50)]
        public string roleName { get; set; }

        [InverseProperty("idRoleNavigation")]
        public virtual ICollection<RoleOption> RoleOption { get; set; }
        [InverseProperty("userRoleNavigation")]
        public virtual ICollection<User> User { get; set; }
    }
}