// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication1.Models
{
    public partial class sp_loginResult
    {
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string ruta { get; set; }
    }
}
