// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication1.Models
{
    public partial class UserCompany
    {
        [Key]
        [StringLength(50)]
        public string userName { get; set; }
        [Key]
        public long companyID { get; set; }
        public bool active { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime record_created { get; set; }
        [Required]
        [StringLength(50)]
        public string record_created_who { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? record_affected { get; set; }
        [StringLength(50)]
        public string record_affected_who { get; set; }

        [ForeignKey(nameof(companyID))]
        [InverseProperty(nameof(Company.UserCompany))]
        public virtual Company company { get; set; }
        [ForeignKey(nameof(userName))]
        [InverseProperty(nameof(User.UserCompany))]
        public virtual User userNameNavigation { get; set; }
    }
}