// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication1.Models
{
    public partial class UserPwdReset
    {
        /// <summary>
        /// Usuario que solicita
        /// </summary>
        [Key]
        [StringLength(50)]
        public string userName { get; set; }
        /// <summary>
        /// A qué correo fue enviado
        /// </summary>
        [Required]
        [StringLength(75)]
        public string emailSended { get; set; }
        /// <summary>
        /// One time password para confirmar
        /// </summary>
        [Required]
        [StringLength(50)]
        public string OTP { get; set; }
        /// <summary>
        /// fecha solicitada
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime dateRequested { get; set; }
        /// <summary>
        /// Fecha máxima válida
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime validUntil { get; set; }
    }
}