// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication1.Models
{
    public partial class UserPasswordHistory
    {
        [Key]
        public long ID { get; set; }
        [Required]
        [StringLength(50)]
        public string userName { get; set; }
        [Required]
        [MaxLength(20)]
        public byte[] password { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime date_added { get; set; }
    }
}